OnlineJudge/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^onlinejudge/', include('onlinejudge.urls')),
    url(r'^admin/', admin.site.urls),
]

onlinejudge/urls.py
from django.conf.urls import url

from . import views

app_name = 'onlinejudge'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^problems/$', views.problems, name='problems'),
    url(r'^problems/(?P<problem_name>[a-zA-Z]+)/$', views.problem_details, name='problem_details'),
    url(r'^submitted/$', views.new_submission, name='new_submission'),
]

onlinejudge/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class User(models.Model):
	user_name = models.CharField(max_length=100)
	user_rating = models.IntegerField(default=0)
	def __str__(self):
		return self.user_name

class Question(models.Model):
	question_name = models.CharField(max_length=100)
	question_description = models.CharField(max_length=10000)
	question_input_file = models.CharField(max_length=200)
	question_output_file = models.CharField(max_length=200)
	def __str__(self):
		return self.question_name

class Submission(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	submission_file = models.FileField(upload_to='documents/', default='background.gif')
	submission_status = models.CharField(max_length=50)
	submission_language = models.CharField(max_length=50)
	submission_time = models.FloatField(default=100.00)

onlinejudge/forms.py
from django import forms

class SubmissionForm(forms.Form):
    #title = forms.CharField(max_length=50)
    filename = forms.FileField(label='Upload your code')

onlinejudge/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.urls import reverse
from django.template import loader
from .forms import SubmissionForm

from .models import User, Question, Submission
from .func import run_file

# Create your views here.

def index(request):
    return render(request, 'onlinejudge/index.html')

def problems(request):
	latest_problems_list = Question.objects.all()[:5]
	template = loader.get_template('onlinejudge/problems.html')
	context = {
		'latest_problems_list': latest_problems_list,
	}
	return HttpResponse(template.render(context, request))

def problem_details(request, problem_name):
	problem = get_object_or_404(Question, question_name=problem_name)
	template = loader.get_template('onlinejudge/details.html')
	context = {
		'problem': problem,
	}
	return HttpResponse(template.render(context, request))

def new_submission(request):
	if request.method == 'POST' and request.FILES['codefile']:
		submission_number = Submission.objects.last().id + 1
		run_file(request.FILES['codefile'])
		template = loader.get_template('onlinejudge/submitted.html')
		context = {
			'submission_number': submission_number,
		}
		return HttpResponse(template.render(context, request))
	else:
		return HttpResponseRedirect(reverse('onlinejudge:problems'))

onlinejudge/templates/onlinejudge/details.html
<html>
<head>
<title>{% if problem %} {{problem.question_name}} {% endif %}</title>
</head>
<body>
{% if problem %}
	<h1>{{problem.question_name}}</h1><br/>
	<p>{{problem.question_description}}</p><br/>
	<form action="{% url 'onlinejudge:new_submission' %}" method="post" enctype="multipart/form-data">
	{% csrf_token %}
	<input type="file" name="codefile"><br/><br/>
	<input type="submit" value="Upload">
	</form>
{% endif %}
</body>
</html>

onlinejudge/templates/onlinejudge/index.html
{% load static %}
<html>
<head>
	<title>Index</title>
	<script class="cssdeck" src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
	<script src="https://code.jquery.com/jquery-1.6.2.min.js"></script>
	<script src="{% static 'onlinejudge/js/pace.js' %}"></script>
	<link href="{% static 'onlinejudge/css/pace-theme-atom.css' %}" rel="stylesheet" />
	<link href="{% static 'onlinejudge/css/style.css' %}" rel="stylesheet" />
	<link href='http://fonts.googleapis.com/css?family=Cookie' rel='stylesheet' type='text/css' />

	<script type="text/javascript">
		jQuery(document).ready(function($) {	
		$('.lightbox_trigger').click(function(e) {
			e.preventDefault();
			if ($('#lightbox').length > 0) {				
				$('#lightbox').show();
			}
			else {
				var lightbox = 
				'<div id="lightbox">' +
					'<p id=\"close\"></p>' +	
				'</div>';
				$('.oj-header-limiter').append(lightbox);
			}
		});
		$('#lightbox').click(function(e) {
			var container = $('#close');
			if (container.is(e.target)) {
				$('#lightbox').hide(200);
			}
		});
	});

	$('document').ready(function(){
		$('input[type="text"], input[type="password"], textarea').focus(function(){
			var background = $(this).attr('id');
			$('#' + background + '-form').addClass('formgroup-active');
			$('#' + background + '-form').removeClass('formgroup-error');
		});
		$('input[type="text"], input[type="password"], textarea').blur(function(){
			var background = $(this).attr('id');
			$('#' + background + '-form').removeClass('formgroup-active');
		});

	function errorfield(field){
		$(field).addClass('formgroup-error');
		console.log(field);	
	}

	$("#loginform").submit(function() {
		var stopsubmit = false;

	if($('#username').val() == "") {
		errorfield('#username-form');
		stopsubmit=true;
	}
	if($('#password').val() == "") {
		errorfield('#password-form');
		stopsubmit=true;
	}
	  if(stopsubmit) return false;
	});
			
	});

	</script>

</head>
<body>
<header class="oj-header">
	<div class="oj-header-limiter">
		<h1><a href="{% url 'onlinejudge:index' %}">Online<span>Judge</span></a></h1>
		<nav>
			<a href="{% url 'onlinejudge:index' %}" class="selected">Home</a>
			<a href="{% url 'onlinejudge:problems' %}">Problems</a>
			<a href="#">Editorials</a>
		</nav>
		<ul>
			<li><a href="#" class="lightbox_trigger">Login</a></li>
			<li><a href="#" class="lightbox_trigger">Sign up</a></li>
		</ul>
	</div>
</header>
<div class="content">
	<div id="lightbox">
	    <img src="{% static 'onlinejudge/images/close.png' %}" id="close" style="width:50px;height:50px"/>
	    <div id="loginform">
	    <!-- <div class="fish"></div> -->
	        <form method="get" action="#">
	        	<div class="formgroup" id="username-form">
				    <label for="email">Your username*</label>
				    <input type="text" id="username" placeholder="User Name" name="username">
				</div>
	        	<div class="formgroup" id="password-form">
				    <label for="message">Your password*</label>
				    <input type="password" id="password" placeholder="Password" name="password">
				</div>
	        	<input type="submit" value="Login" />
	        </form>
	    </div>
	</div>
	<!--<a href="{% url 'onlinejudge:problems'%}"><button>Solve Problems</button></a>
	<a href="#"><button>View Profile</button></a>-->
</div>
</body>
</html>

onlinejudge/templates/onlinejudge/problems.html
{% load static %}
<html>
<head>
<title>Problems</title>
<script class="cssdeck" src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-1.6.2.min.js"></script>
<script src="{% static 'onlinejudge/js/pace.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'onlinejudge/css/style.css' %}" />
<link href="{% static 'onlinejudge/css/pace-theme-atom.css' %}" rel="stylesheet" />
<link href='http://fonts.googleapis.com/css?family=Cookie' rel='stylesheet' type='text/css'>
</head>
<body>

<header class="oj-header">
	<div class="oj-header-limiter">
		<h1><a href="{% url 'onlinejudge:index' %}">Online<span>Judge</span></a></h1>
		<nav>
			<a href="{% url 'onlinejudge:index' %}">Home</a>
			<a href="{% url 'onlinejudge:problems' %}" class="selected">Problems</a>
			<a href="#">Editorials</a>
		</nav>
		<ul>
			<li><a href="#" class="lightbox_trigger">Login</a></li>
			<li><a href="#" class="lightbox_trigger">Sign up</a></li>
		</ul>
	</div>
</header>

{% if latest_problems_list %}
    <ul>
    {% for problem in latest_problems_list %}
        <li><a href="{% url 'onlinejudge:problem_details' problem.question_name %}">{{ problem.question_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No questions are available.</p>
{% endif %}
</body>
</html>

onlinejudge/templates/onlinejudge/submitted.html
<html>
<head>
<title>Submission Successful</title>
</head>
<body>
	<h1>Successful Submission</h1><br/>
	<p>{{submission_number}}</p><br/>
	<a href="{% url 'onlinejudge:index' %}"><button>Home</button></a>
</body>
</html>